### ISSUE TITLE
진동모듈이 너무 약하다

### ISSUE THREAD

**Issue by b-chae** [b-chae/VibrationFromWarningForHearingImpaired#39]
진동모듈 최대 세기를 확인해봤을 때, 진동이 매트리스 전체를 울릴 정도의 세기가 아니다.

**Comment by asomeJay** [comment]
1. 강한 빛을 이용한다(지금은 자체 빛이 약하니까 꺨 때까지 반짝이는 것도 좋을듯)

**Comment by dizwe** [comment]
- 더 좋은 진동 모듈을 사용하는 방법
- 베개에 연결하는 방법
- 스마트워치 연동(대신에 만들 수 있는 시간이 충분치 않음)

**Comment by asomeJay** [comment]
청색광과 멜라토닌 분비의 관계가 입증된 바 있다. 청색 LED 전구를 이용하는 방법도 고려해봄직하다.

만약 농인이 침대가 아니라 바닥에서 잔다면 어떻게 신호를 줄 것인가?

**Comment by b-chae** [comment]
(오종인 멘토님 의견 반영)
실제제품이 아닌 프로토타입을 만드는 만큼 선해결해야할 문제가 아니라고 판단

**Comment by b-chae** [comment]
- 웨어러블 기기 전환을 위한 스텝!
- 작은 브레드 보드 구매
- 블루투스 구매 : 블루투스를 사용하여 두 개의 아두이노간 무선 통신을 하려고 합니다 :)
