### ISSUE TITLE
Siren이나 아기 울음이 판별 되었을 때 얼마나 지속해서 울릴것인가?

### ISSUE THREAD

**Issue by dizwe** [b-chae/VibrationFromWarningForHearingImpaired#46]

**Comment by dizwe** [comment]
벼리, 민호 : 아기 안울면 꺼지고 울면 켜지게
재원 : 사람이 일어나서 끄면 좋겠다.
 - do not disturb 모드로 몇분동안 멈추기
 - 버튼 만들기???

**Comment by asomeJay** [comment]
버튼이 있으면 좋을 것 같긴합니다. 계속 생각해봐욥!

**Comment by dizwe** [comment]
30초 이상 소리가 안나면 꺼지게 함
