### ISSUE TITLE
서버에 무리가 안가게 하기 위해 짧은 시간 판별하고 한동안 쉬었다가 보내도록 만들기

### ISSUE THREAD

**Issue by dizwe** [b-chae/VibrationFromWarningForHearingImpaired#47]
전미정 멘토님 의견 반영
a. 3초하고 3초 쉬고
b. 1초하고 5초 쉬고
c. 5초 하고 5초 쉬고

**Comment by b-chae** [comment]
1초 동안은 아기가 우는 울음이나 사이렌 소리 패턴이 잘 안담길것 같다 ,,,

**Comment by dizwe** [comment]
5초 하고 5초 쉬면 사이렌이 잠깐 울리다 말았을 때에도 10초라는 시간이 사이렌으로 판별되는 문제
자주 판별될 수 있도록 하는게 더 좋을 듯

**Comment by asomeJay** [comment]
그러면 3초 / 3초로 하는 건 어때요. 1초는 너무 짧고 5초는 너무 기네요

**Comment by dizwe** [comment]
일정 amplitude 이상일때만 업로드 하게 하면 어때요??

**Comment by b-chae** [comment]
그게 더 말이 되는거 같아요.
계속 듣고 있다가 소리가 날때 3초 녹음 시작하는걸로 바꿀게요

**Comment by dizwe** [comment]
전송하고 판별하는데 이미 시간이 좀 걸려서 따로 시간을 둘 필요가 없었음
