### ISSUE TITLE
StatusCode -11 Error

### ISSUE THREAD

**Issue by b-chae** [b-chae/VibrationFromWarningForHearingImpaired#48]
- POST후 받을 때 에러가 납니다 ㅠㅅㅜ

**Comment by asomeJay** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPClient/src/HTTPClient.h
일단 저희 에러 코드는
#define HTTPC_ERROR_READ_TIMEOUT        (-11)
이거 같아요.
HTTPClient.h 에 정의되어있는 에러코드에요
그리고 이 에러코드를 쓰는 곳이 sendRequest의 마지막에 있는 그림 1의 저 노란색으로 칠한 함수입니다.
handleHeaderResponse() 함수를 호출하면 그림2로 이동합니다. 저기서 Time Out이 발생해요.  tcp_time_out보다 Read하는 시간이 길다는건데, 거 tcp_time을 HTTPClient.h 에서 정의합니다.
그러므로 미봉책이긴하지만, 저 #define 되어있는 DEFAULT TIME을 늘리면 적어도 지금 나는 그 에러는 안나지않을까 하는게 제 생각입니다!

**Comment by b-chae** [comment]
Timeout error 였군요 ㅇㅅㅇ

**Comment by asomeJay** [comment]
그런 듯 하네요

**Comment by dizwe** [comment]
https://github.com/esp8266/Arduino/issues/3780
https://github.com/espressif/arduino-esp32/issues/2169
이 링크도 참고 부탁해요~

**Comment by dizwe** [comment]
ML 판별시간 flask로 늘려서 해결 완료!
