### ISSUE TITLE
웨어러블 하게는 안될까?

### ISSUE THREAD

**Issue by asomeJay** [b-chae/VibrationFromWarningForHearingImpaired#50]
멘토분들께서 계속 말씀하시는 부분 ㅠ 웨어러블...

**Comment by b-chae** [comment]
- HC 05 블루투스 모듈 이용하여 테스트하기 !
- 아두이노 1 : HC05마스터 / 소리를 녹음하여 전송, 판단된 결과값을 아두이노 2에게 블루투스 통신
- 아두이노 2 : HC05슬레이브 / 진동또는 LED 출력
- 페어링 테스트 완료 👍

**Comment by asomeJay** [comment]
So good!!!!
