### ISSUE TITLE
아두이노 조립하고 실험

### ISSUE THREAD

**Issue by dizwe** [b-chae/VibrationFromWarningForHearingImpaired#9]
- 도착 기다려야 함
- 납땜 해야함
- 코드 시도해봐 야 함

**Comment by b-chae** [comment]
배송 완료되었습니다 -!!

**Comment by b-chae** [comment]
납땜완료 -!! (feat. 아빠)

**Comment by b-chae** [comment]
- 10초짜리 wav파일을 1024 -> 256으로 줄여서 저장 : 78kb 정도의 크기
- 8비트 대신 16비트로 저장해보고 크기와 품질 비교하기

**Comment by b-chae** [comment]
- POST를 사용하여 wav파일 서버에 전달 성공
